export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const OTP_LOADING = 'OTP_LOADING';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_ERROR = 'OTP_ERROR';

 